### ISSUE TITLE
ng-href not working on mobile

### ISSUE THREAD

**Issue by Microsmsm** [Microsmsm/Dawaey#1]
when I press the ion list it should move me to the link but that don't happed
https://github.com/Microsmsm/Dawaey/blob/master/templates/tab-search.html
Line 11

**Comment by amrography** [comment]
`href` is attribute for anchor tags only, since you are change your date dynamically you add `ng-href` to anchor tag `<a ng-href="{{link}}"></a>`

You have 2 options to make your link work:
- replace `<ion-item>` with `<a>`
- replace 'ng-href` with `ui-sref`

_You also have wrong closed tag on line 10_

**Comment by Microsmsm** [comment]
in the `config.xml` file write the following `<allow-navigation href="*" />` inside the `<platform name="android">` tag

**Comment by amrography** [comment]
You are trying to go to link outside the application. You need to use plugins like this:
http://ngcordova.com/docs/plugins/inAppBrowser/
